-- ============================
-- 50K SALES RECORDS DATASET
-- Table: SALES_RECORDS_50K
-- View: VW_SALES_RECORDS_ENRICHED
-- ============================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS SALES_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SALES_ANALYTICS.PUBLIC;

USE DATABASE SALES_ANALYTICS;
USE SCHEMA PUBLIC;

-- 1) Table (matches your Sigma columns)
CREATE OR REPLACE TABLE SALES_RECORDS_50K (
  REGION          STRING,
  COUNTRY         STRING,
  CATEGORY        STRING,
  CHANNEL         STRING,
  ORDER_PRIORITY  STRING,
  ORDER_DATE      DATE,
  ORDER_ID        NUMBER,
  SHIP_DATE       DATE,
  UNITS_SOLD      NUMBER(18,2),
  UNIT_PRICE      NUMBER(18,2),
  UNIT_COST       NUMBER(18,2),
  REVENUE         NUMBER(18,2),
  TOTAL_COST      NUMBER(18,2),
  PROFIT          NUMBER(18,2)
);

-- 2) File format + stage
CREATE OR REPLACE FILE FORMAT FF_SALES_50K
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE STG_SALES_50K
  FILE_FORMAT = FF_SALES_50K;

-- 3) Load
-- Upload your sales_records_50k.csv into STG_SALES_50K (Snowsight > Data > Databases > Stages > upload)
COPY INTO SALES_RECORDS_50K
FROM @STG_SALES_50K/sales_records_50k.csv;

-- 4) If your CSV does NOT include revenue/total_cost/profit, create a view that derives them safely:
CREATE OR REPLACE VIEW VW_SALES_RECORDS_ENRICHED AS
SELECT
  REGION,
  COUNTRY,
  CATEGORY,
  CHANNEL,
  ORDER_PRIORITY,
  ORDER_DATE,
  ORDER_ID,
  SHIP_DATE,
  UNITS_SOLD,
  UNIT_PRICE,
  UNIT_COST,

  -- Use existing columns if present, otherwise calculate
  COALESCE(REVENUE, UNITS_SOLD * UNIT_PRICE) AS REVENUE_CALC,
  COALESCE(TOTAL_COST, UNITS_SOLD * UNIT_COST) AS TOTAL_COST_CALC,
  COALESCE(PROFIT, (UNITS_SOLD * UNIT_PRICE) - (UNITS_SOLD * UNIT_COST)) AS PROFIT_CALC,

  CASE
    WHEN COALESCE(REVENUE, UNITS_SOLD * UNIT_PRICE) = 0 THEN NULL
    ELSE COALESCE(PROFIT, (UNITS_SOLD * UNIT_PRICE) - (UNITS_SOLD * UNIT_COST))
         / COALESCE(REVENUE, UNITS_SOLD * UNIT_PRICE)
  END AS MARGIN_PCT
FROM SALES_RECORDS_50K;

-- Validation
SELECT COUNT(*) AS ROWS_CNT FROM SALES_RECORDS_50K;
SELECT * FROM VW_SALES_RECORDS_ENRICHED LIMIT 10;
